title = "elijahcaine.me"
base_url = "/"
description = "A blog about tech, media, and art"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

theme = "zola-bearblog"

generate_feeds = true
feed_filenames = ["atom.xml"]

taxonomies = [
  { name = "tags", feed = true },
]

[translations]
no_posts = "No posts yet"
remove_filter = "Remove filter"
filtering_for = "Filtering for"
made_with = "Made with"
table_of_contents = "Table of contents"
language = "language"
site = "site"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "1337"

[extra]
favicon = "/favicon.ico"
date_format = "%a %d %b %Y"
webserver_sends_csp_headers = true
language_switcher = false
hide_made_with_line = true

[extra.table_of_contents]
show = true
max_level = 2
visible_on_load = true

[[extra.main_menu]]
name = "(ğŸ  elijahcaine.me)"
url = "@/_index.md"

[[extra.main_menu]]
name = "(ğŸ•¹ï¸ games)"
url = "https://games.elijah.run"

[[extra.main_menu]]
name = "(ğŸ™ github ğŸ±)"
url = "https://github.com/pop"

[[extra.main_menu]]
name = "(ğŸ‘” resume)"
url = "/Elijah Voigt.pdf"
